import java.util.LinkedList;
/**
 * The User class represents a user with his associated information like  name, and email .
 * It provides methods to get and set the user's details

 */
public class User {

    private int id;
    private String name;
    private String email;
    static int userIdGenerator = 0;

    /**
     * Constructs a new User with the specified name and email.
     * The user's ID is auto-generated by incrementing userIdGenerator .
     *
     * @param name  the name of the user
     * @param email the email address of the user
     */
    public User(String name, String email) {
        this.id = userIdGenerator++;
        this.name = name;
        this.email = email;
    }

    /**
     * To get the user's  ID
     * @return the ID of the user
     */
    public int getId() {
        return id;
    }

    /**
     * To change the user's  ID.
     * @param id the new ID to be assigned to this user
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of this user.
     * @return the name of the user
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this user.
     * @param name the new name to be assigned to this user
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * gets the email address of this user.
     * @return the email address of the user
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of this user.
     * @param email the new email address to be assigned to this user
     */
    public void setEmail(String email) {
        this.email = email;
    }
}











